package POJO;
// Generated Mar 27, 2012 11:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Emprestimo generated by hbm2java
 */
public class Emprestimo  implements java.io.Serializable {

/* Falta statos do emprestimo*/
     private int idemprestimo;
     private Usuario usuario;
     private Date dataEmprestimo;
     private Date dataDevolucao;
     private Integer usuario_1;
     private Integer codigoObra;
     private Set revistas = new HashSet(0);
     private Set livros = new HashSet(0);
     private Set midiaDigitals = new HashSet(0);

    public Emprestimo() {
    }

	
    public Emprestimo(int idemprestimo, Usuario usuario) {
        this.idemprestimo = idemprestimo;
        this.usuario = usuario;
    }
    public Emprestimo(int idemprestimo, Usuario usuario, Date dataEmprestimo, Date dataDevolucao, Integer usuario_1, Integer codigoObra, Set revistas, Set livros, Set midiaDigitals) {
       this.idemprestimo = idemprestimo;
       this.usuario = usuario;
       this.dataEmprestimo = dataEmprestimo;
       this.dataDevolucao = dataDevolucao;
       this.usuario_1 = usuario_1;
       this.codigoObra = codigoObra;
       this.revistas = revistas;
       this.livros = livros;
       this.midiaDigitals = midiaDigitals;
    }
   
    public int getIdemprestimo() {
        return this.idemprestimo;
    }
    
    public void setIdemprestimo(int idemprestimo) {
        this.idemprestimo = idemprestimo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getDataEmprestimo() {
        return this.dataEmprestimo;
    }
    
    public void setDataEmprestimo(Date dataEmprestimo) {
        this.dataEmprestimo = dataEmprestimo;
    }
    public Date getDataDevolucao() {
        return this.dataDevolucao;
    }
    
    public void setDataDevolucao(Date dataDevolucao) {
        this.dataDevolucao = dataDevolucao;
    }
    public Integer getUsuario_1() {
        return this.usuario_1;
    }
    
    public void setUsuario_1(Integer usuario_1) {
        this.usuario_1 = usuario_1;
    }
    public Integer getCodigoObra() {
        return this.codigoObra;
    }
    
    public void setCodigoObra(Integer codigoObra) {
        this.codigoObra = codigoObra;
    }
    public Set getRevistas() {
        return this.revistas;
    }
    
    public void setRevistas(Set revistas) {
        this.revistas = revistas;
    }
    public Set getLivros() {
        return this.livros;
    }
    
    public void setLivros(Set livros) {
        this.livros = livros;
    }
    public Set getMidiaDigitals() {
        return this.midiaDigitals;
    }
    
    public void setMidiaDigitals(Set midiaDigitals) {
        this.midiaDigitals = midiaDigitals;
    }




}


