package POJO;
// Generated Mar 27, 2012 11:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Livro generated by hbm2java
 */
public class Livro  implements java.io.Serializable {


     private int idlivro;
     private Emprestimo emprestimo;
     private String titulo;
     private Integer isbn;
     private Integer idEditora;
     private String edicao;
     private Integer ano;
     private Integer quantidade;
     private Integer raridade;
     private Date dataCadastro;
     private Integer codigo;
     private Date dataLancamento;
     private Set autors = new HashSet(0);

    public Livro() {
    }

	
    public Livro(int idlivro, Emprestimo emprestimo) {
        this.idlivro = idlivro;
        this.emprestimo = emprestimo;
    }
    public Livro(int idlivro, Emprestimo emprestimo, String titulo, Integer isbn, Integer idEditora, String edicao, Integer ano, Integer quantidade, Integer raridade, Date dataCadastro, Integer codigo, Date dataLancamento, Set autors) {
       this.idlivro = idlivro;
       this.emprestimo = emprestimo;
       this.titulo = titulo;
       this.isbn = isbn;
       this.idEditora = idEditora;
       this.edicao = edicao;
       this.ano = ano;
       this.quantidade = quantidade;
       this.raridade = raridade;
       this.dataCadastro = dataCadastro;
       this.codigo = codigo;
       this.dataLancamento = dataLancamento;
       this.autors = autors;
    }
   
    public int getIdlivro() {
        return this.idlivro;
    }
    
    public void setIdlivro(int idlivro) {
        this.idlivro = idlivro;
    }
    public Emprestimo getEmprestimo() {
        return this.emprestimo;
    }
    
    public void setEmprestimo(Emprestimo emprestimo) {
        this.emprestimo = emprestimo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Integer getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(Integer isbn) {
        this.isbn = isbn;
    }
    public Integer getIdEditora() {
        return this.idEditora;
    }
    
    public void setIdEditora(Integer idEditora) {
        this.idEditora = idEditora;
    }
    public String getEdicao() {
        return this.edicao;
    }
    
    public void setEdicao(String edicao) {
        this.edicao = edicao;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    public Integer getRaridade() {
        return this.raridade;
    }
    
    public void setRaridade(Integer raridade) {
        this.raridade = raridade;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Date getDataLancamento() {
        return this.dataLancamento;
    }
    
    public void setDataLancamento(Date dataLancamento) {
        this.dataLancamento = dataLancamento;
    }
    public Set getAutors() {
        return this.autors;
    }
    
    public void setAutors(Set autors) {
        this.autors = autors;
    }




}


