package POJO;
// Generated Mar 27, 2012 11:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MidiaDigital generated by hbm2java
 */
public class MidiaDigital  implements java.io.Serializable {


     private int idmidiaDigital;
     private Emprestimo emprestimo;
     private String titulo;
     private String edicao;
     private Date dataLancamento;
     private Integer quantidade;
     private Integer disponibilidade;
     private Integer raridade;
     private Date dataCadastro;
     private String elenco;
     private String recomendacao;
     private String regiao;
     private String tempo;
     private Integer codigo;
     private Integer estudio;
     private Set estudios = new HashSet(0);

    public MidiaDigital() {
    }

	
    public MidiaDigital(int idmidiaDigital, Emprestimo emprestimo) {
        this.idmidiaDigital = idmidiaDigital;
        this.emprestimo = emprestimo;
    }
    public MidiaDigital(int idmidiaDigital, Emprestimo emprestimo, String titulo, String edicao, Date dataLancamento, Integer quantidade, Integer disponibilidade, Integer raridade, Date dataCadastro, String elenco, String recomendacao, String regiao, String tempo, Integer codigo, Integer estudio, Set estudios) {
       this.idmidiaDigital = idmidiaDigital;
       this.emprestimo = emprestimo;
       this.titulo = titulo;
       this.edicao = edicao;
       this.dataLancamento = dataLancamento;
       this.quantidade = quantidade;
       this.disponibilidade = disponibilidade;
       this.raridade = raridade;
       this.dataCadastro = dataCadastro;
       this.elenco = elenco;
       this.recomendacao = recomendacao;
       this.regiao = regiao;
       this.tempo = tempo;
       this.codigo = codigo;
       this.estudio = estudio;
       this.estudios = estudios;
    }
   
    public int getIdmidiaDigital() {
        return this.idmidiaDigital;
    }
    
    public void setIdmidiaDigital(int idmidiaDigital) {
        this.idmidiaDigital = idmidiaDigital;
    }
    public Emprestimo getEmprestimo() {
        return this.emprestimo;
    }
    
    public void setEmprestimo(Emprestimo emprestimo) {
        this.emprestimo = emprestimo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getEdicao() {
        return this.edicao;
    }
    
    public void setEdicao(String edicao) {
        this.edicao = edicao;
    }
    public Date getDataLancamento() {
        return this.dataLancamento;
    }
    
    public void setDataLancamento(Date dataLancamento) {
        this.dataLancamento = dataLancamento;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    public Integer getDisponibilidade() {
        return this.disponibilidade;
    }
    
    public void setDisponibilidade(Integer disponibilidade) {
        this.disponibilidade = disponibilidade;
    }
    public Integer getRaridade() {
        return this.raridade;
    }
    
    public void setRaridade(Integer raridade) {
        this.raridade = raridade;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public String getElenco() {
        return this.elenco;
    }
    
    public void setElenco(String elenco) {
        this.elenco = elenco;
    }
    public String getRecomendacao() {
        return this.recomendacao;
    }
    
    public void setRecomendacao(String recomendacao) {
        this.recomendacao = recomendacao;
    }
    public String getRegiao() {
        return this.regiao;
    }
    
    public void setRegiao(String regiao) {
        this.regiao = regiao;
    }
    public String getTempo() {
        return this.tempo;
    }
    
    public void setTempo(String tempo) {
        this.tempo = tempo;
    }
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Integer getEstudio() {
        return this.estudio;
    }
    
    public void setEstudio(Integer estudio) {
        this.estudio = estudio;
    }
    public Set getEstudios() {
        return this.estudios;
    }
    
    public void setEstudios(Set estudios) {
        this.estudios = estudios;
    }




}


