package POJO;
// Generated Mar 27, 2012 11:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Revista generated by hbm2java
 */
public class Revista  implements java.io.Serializable {


     private int idrevista;
     private Emprestimo emprestimo;
     private String titulo;
     private String edicao;
     private Integer ano;
     private Integer quantidade;
     private String disponibilidade;
     private String raridade;
     private Date dataCadastro;
     private Integer codigo;
     private Set editoras = new HashSet(0);

    public Revista() {
    }

	
    public Revista(int idrevista, Emprestimo emprestimo) {
        this.idrevista = idrevista;
        this.emprestimo = emprestimo;
    }
    public Revista(int idrevista, Emprestimo emprestimo, String titulo, String edicao, Integer ano, Integer quantidade, String disponibilidade, String raridade, Date dataCadastro, Integer codigo, Set editoras) {
       this.idrevista = idrevista;
       this.emprestimo = emprestimo;
       this.titulo = titulo;
       this.edicao = edicao;
       this.ano = ano;
       this.quantidade = quantidade;
       this.disponibilidade = disponibilidade;
       this.raridade = raridade;
       this.dataCadastro = dataCadastro;
       this.codigo = codigo;
       this.editoras = editoras;
    }
   
    public int getIdrevista() {
        return this.idrevista;
    }
    
    public void setIdrevista(int idrevista) {
        this.idrevista = idrevista;
    }
    public Emprestimo getEmprestimo() {
        return this.emprestimo;
    }
    
    public void setEmprestimo(Emprestimo emprestimo) {
        this.emprestimo = emprestimo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getEdicao() {
        return this.edicao;
    }
    
    public void setEdicao(String edicao) {
        this.edicao = edicao;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    public String getDisponibilidade() {
        return this.disponibilidade;
    }
    
    public void setDisponibilidade(String disponibilidade) {
        this.disponibilidade = disponibilidade;
    }
    public String getRaridade() {
        return this.raridade;
    }
    
    public void setRaridade(String raridade) {
        this.raridade = raridade;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Set getEditoras() {
        return this.editoras;
    }
    
    public void setEditoras(Set editoras) {
        this.editoras = editoras;
    }




}


