package POJO;
// Generated Mar 27, 2012 11:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private int idtipoUsuario;
     private String nomeTipo;
     private Boolean boolTipo;
     private Set usuarios = new HashSet(0);

    public TipoUsuario() {
    }

	
    public TipoUsuario(int idtipoUsuario) {
        this.idtipoUsuario = idtipoUsuario;
    }
    public TipoUsuario(int idtipoUsuario, String nomeTipo, Boolean boolTipo, Set usuarios) {
       this.idtipoUsuario = idtipoUsuario;
       this.nomeTipo = nomeTipo;
       this.boolTipo = boolTipo;
       this.usuarios = usuarios;
    }
   
    public int getIdtipoUsuario() {
        return this.idtipoUsuario;
    }
    
    public void setIdtipoUsuario(int idtipoUsuario) {
        this.idtipoUsuario = idtipoUsuario;
    }
    public String getNomeTipo() {
        return this.nomeTipo;
    }
    
    public void setNomeTipo(String nomeTipo) {
        this.nomeTipo = nomeTipo;
    }
    public Boolean getBoolTipo() {
        return this.boolTipo;
    }
    
    public void setBoolTipo(Boolean boolTipo) {
        this.boolTipo = boolTipo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


