package POJO;
// Generated Mar 27, 2012 11:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private TipoUsuario tipoUsuario;
     private String login;
     private String senha;
     private String email;
     private Set dadosUsuarios = new HashSet(0);
     private Set emprestimos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Usuario(TipoUsuario tipoUsuario, String login, String senha, String email, Set dadosUsuarios, Set emprestimos) {
       this.tipoUsuario = tipoUsuario;
       this.login = login;
       this.senha = senha;
       this.email = email;
       this.dadosUsuarios = dadosUsuarios;
       this.emprestimos = emprestimos;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getDadosUsuarios() {
        return this.dadosUsuarios;
    }
    
    public void setDadosUsuarios(Set dadosUsuarios) {
        this.dadosUsuarios = dadosUsuarios;
    }
    public Set getEmprestimos() {
        return this.emprestimos;
    }
    
    public void setEmprestimos(Set emprestimos) {
        this.emprestimos = emprestimos;
    }




}


